# Jekyll configuration for AFNM Example Mod Documentation

title: "AFNM Example Mod Documentation"
description: "Documentation for the Ascend from Nine Mountains Example Mod"

# Theme
theme: just-the-docs

# GitHub Pages settings
url: "https://lyeeedar.github.io"
baseurl: "/Cultivation"

# Navigation
nav_sort: case_insensitive

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Footer
footer_content: "AFNM Example Mod Documentation"

# Color scheme
color_scheme: dark