title: 'Ascend from Nine Mountains - Modding Guide'
description: 'Comprehensive documentation for modding the cultivation game'
baseurl: '/AfnmExampleMod'
url: 'https://lyeeedar.github.io'

# Jekyll configuration
remote_theme: just-the-docs/just-the-docs@v0.7.0
markdown: kramdown
highlighter: rouge
color_scheme: custom

# Collections for organizing documentation
collections:
  guides:
    output: true
    permalink: /:collection/:name/
  assets:
    output: true
    permalink: /:collection/:name/
  concepts:
    output: true
    permalink: /:collection/:name/

# Just the Docs settings
search_enabled: false
heading_anchors: true
nav_sort: case_sensitive
back_to_top: true
back_to_top_text: "Back to top"


# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src
  - dist
  - scripts
  - builds
