title: 'Ascend from Nine Mountains - Modding Guide'
description: 'Comprehensive documentation for modding the cultivation game'
baseurl: '/AfnmExampleMod'
url: 'https://lyeeedar.github.io'

# Jekyll configuration
remote_theme: mmistakes/minimal-mistakes@4.24.0
markdown: kramdown
highlighter: rouge
minimal_mistakes_skin: "dark" # Use dark theme as base
search: false
breadcrumbs: false

# Collections for organizing documentation
collections:
  guides:
    output: true
    permalink: /:collection/:name/
  assets:
    output: true
    permalink: /:collection/:name/
  concepts:
    output: true
    permalink: /:collection/:name/

# Default layout settings
defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: "docs"


# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src
  - dist
  - scripts
  - builds
