title: 'Ascend from Nine Mountains - Modding Guide'
description: 'Comprehensive documentation for modding the cultivation game'
baseurl: '/AfnmExampleMod'
url: 'https://lyeeedar.github.io'

# Jekyll configuration
remote_theme: pages-themes/midnight@v0.2.0
markdown: kramdown
highlighter: rouge

# Collections for organizing documentation
collections:
  guides:
    output: true
    permalink: /:collection/:name/
  assets:
    output: true
    permalink: /:collection/:name/
  concepts:
    output: true
    permalink: /:collection/:name/

# Navigation
header_pages:
  - index.md
  - getting-started.md

# Sidebar Navigation
sidebar:
  - title: 'Getting Started'
    children:
      - title: 'Home'
        url: /
      - title: 'Getting Started'
        url: /getting-started/

  - title: 'Core Concepts'
    children:
      - title: 'Scaling System'
        url: /concepts/concepts-scaling/
      - title: 'Flags & State'
        url: /concepts/concepts-flags/

  - title: 'Events System'
    children:
      - title: 'Events Overview'
        url: /concepts/concepts-events/
      - title: 'Triggered Events'
        url: /concepts/concepts-triggered-events/
      - title: 'Event Steps'
        url: /concepts/concepts-event-steps/

  - title: 'Event Step Types'
    children:
      - title: 'Text & Speech'
        url: /concepts/concepts-event-steps-text-speech/
      - title: 'Choices'
        url: /concepts/concepts-event-steps-choices/
      - title: 'State Management'
        url: /concepts/concepts-event-steps-state/
      - title: 'Items & Resources'
        url: /concepts/concepts-event-steps-items/
      - title: 'Combat & Challenges'
        url: /concepts/concepts-event-steps-combat/
      - title: 'Character Interaction'
        url: /concepts/concepts-event-steps-characters/
      - title: 'World & Location'
        url: /concepts/concepts-event-steps-world/
      - title: 'Advanced Systems'
        url: /concepts/concepts-event-steps-advanced/

  - title: 'Buffs & Resources'
    children:
      - title: 'Buffs Overview'
        url: /concepts/concepts-buffs/
      - title: 'Combat Buffs'
        url: /concepts/concepts-buffs-combat-buffs/
      - title: 'Crafting Buffs'
        url: /concepts/concepts-buffs-crafting-buffs/
      - title: 'Design Patterns'
        url: /concepts/concepts-buffs-design-patterns/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src
  - dist
  - scripts
  - builds
